# AI Command Auditor Configuration Template
# Copy this file to config.yml and modify as needed

# Application Settings
app:
  name: "AI Command Auditor"
  version: "0.1.0"
  debug: false
  log_level: "INFO"

# Logging Configuration
logging:
  # Log file location (relative to project root)
  log_file: "logs/auditor.log"

  # Log rotation settings
  max_file_size: "10MB"
  backup_count: 5

  # Log format
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

  # Console output
  console: true

  # Log levels: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"

# Command Analysis Settings
analysis:
  # Enable/disable different analysis types
  security_analysis: true
  performance_analysis: true
  compliance_analysis: true

  # Analysis thresholds
  security:
    risk_threshold: 0.7
    scan_timeout: 30  # seconds

  performance:
    memory_threshold: 80  # percentage
    cpu_threshold: 90     # percentage
    timeout: 60          # seconds

  # Command patterns to monitor
  patterns:
    suspicious_commands:
      - "rm -rf"
      - "chmod 777"
      - "sudo su"
      - "curl.*|.*sh"

    high_risk_operations:
      - "database.*drop"
      - "user.*delete"
      - "permission.*modify"

# Reporting Configuration
reporting:
  # Output formats
  formats:
    - "json"
    - "html"
    - "pdf"

  # Report storage
  output_dir: "data/output/reports"

  # Report retention (days)
  retention_days: 30

  # Email notifications (if configured)
  notifications:
    enabled: false
    recipients: []
    smtp_server: ""
    smtp_port: 587

# Data Storage Settings
data:
  # Input data directory
  input_dir: "data/input"

  # Output data directory
  output_dir: "data/output"

  # Sample data directory
  samples_dir: "data/samples"

  # Data retention policy (days)
  retention:
    raw_data: 90
    processed_data: 365
    reports: 730

# Security Settings
security:
  # Enable encryption for sensitive data
  encryption:
    enabled: true
    algorithm: "AES-256"

  # Access control
  access_control:
    enabled: true
    require_auth: false

  # Audit logging
  audit_log:
    enabled: true
    file: "logs/audit.log"

# Performance Settings
performance:
  # Resource limits
  max_memory_usage: "2GB"
  max_cpu_usage: 80  # percentage

  # Parallel processing
  max_workers: 4

  # Cache settings
  cache:
    enabled: true
    ttl: 3600  # seconds
    max_size: "100MB"

# Integration Settings
integrations:
  # GitHub CLI
  github:
    enabled: false
    token: ""  # Set via environment variable GH_TOKEN

  # Docker
  docker:
    enabled: true
    socket: "/var/run/docker.sock"

  # External APIs
  apis:
    enabled: false
    endpoints: {}

# Development Settings (only for dev environment)
development:
  # Enable debug mode
  debug: true

  # Hot reload
  hot_reload: true

  # Test data
  use_test_data: true

  # Mock external services
  mock_services: true

# Environment Variables Mapping
# These settings can be overridden by environment variables
env_vars:
  log_level: "LOG_LEVEL"
  debug: "DEBUG_MODE"
  github_token: "GH_TOKEN"
  database_url: "DATABASE_URL"
